export const ROLES = {
  ADMIN: 'ADMIN',
  COORDINATOR: 'COORDINATOR',
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT'
};

export const TEACHER_CATEGORIES = {
  METHODOLOGICAL: 'METHODOLOGICAL',
  THEMATIC: 'THEMATIC',
  EVALUATOR: 'EVALUATOR'
};

export const PROJECT_STATUS = ['BORRADOR', 'ENVIADO', 'EN_EVALUACION', 'EVALUADO', 'CERRADO'];
export const ASSIGNMENT_STATUS = ['PENDIENTE', 'EN_PROCESO', 'COMPLETADA'];
export const EVALUATION_STATUS = ['BORRADOR', 'ENVIADA'];
